name: fitapp
description: "Rutinas de ejercicio personalizadas por nivel."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.0
  cached_network_image: ^3.4.0
  flutter_body_atlas: ^0.1.4
  flutter_3d_controller: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/data/exercises.json
    - assets/models/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png
  adaptive_icon_background: "#0D1117"
  adaptive_icon_foreground: assets/icon/icon_fg.png
  remove_alpha_ios: true
