// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKFKetMQriw4RwsZZenbesKPcKe2E5vT8',
    appId: '1:1085443948857:android:bbf197d5532b2665b268e8',
    messagingSenderId: '1085443948857',
    projectId: 'fitapp-f888e',
    storageBucket: 'fitapp-f888e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCngRx6j2txRpGdsfEOzHPsQ_srWYarNEk',
    appId: '1:1085443948857:ios:4fd353ea66cd21d0b268e8',
    messagingSenderId: '1085443948857',
    projectId: 'fitapp-f888e',
    storageBucket: 'fitapp-f888e.firebasestorage.app',
    androidClientId: '1085443948857-5lspg72siiqul8as7vf9ndijlugdhjib.apps.googleusercontent.com',
    iosClientId: '1085443948857-d04ag37jj09brgh61g4c516uet71v58a.apps.googleusercontent.com',
    iosBundleId: 'com.fitapp.fitapp',
  );
}
